spring.application.name=backend-saku
spring.jackson.time-zone=Asia/Jakarta
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

## Auth
app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-ttl-minutes=15
app.otp.expiry-minutes=${OTP_EXPIRY_MINUTES:5}

app.security.cors-allowed-origins=${CORS_ALLOWED_ORIGINS:https://saku-app-fp.vercel.app,http://localhost:3000,http://localhost:5173,http://localhost:4200,http://localhost:62302}
app.redis.key-prefix=${REDIS_KEY_PREFIX:${spring.profiles.active:dev}}
app.redis.host=${REDIS_HOST}
app.redis.port=${REDIS_PORT}
app.redis.timeout=${REDIS_TIMEOUT}
app.redis.username=${REDIS_USERNAME}
app.redis.password=${REDIS_PASSWORD}
app.redis.lettuce-pool-max-active=100
app.redis.lettuce-pool-max-wait=1ms
app.redis.lettuce-pool-max-idle=50
app.redis.lettuce-pool-min-idle=10


# JPA & Schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:saku}
spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA:saku}

# Mail SMTP Configuration (Gmail)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

logging.level.org.hibernate.orm.jdbc.bind=TRACE

# SpringDoc OpenAPI Documentation (Scalar as primary UI)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false